planner:
  gripper: "hanyang"
  visualize: True
  show_finger_path: True
  # visualize: False
  # show_finger_path: False
  swipe_r_margin: 0.035 # unit: m
  swipe_a_margin: 5.0 # unit: deg
  swipe_angle: 15.0   # init:deg
  swipe_speed: 0.07   # unit:m/s
  height: 0.015

gripper:
  hanyang:
    width: 0.10
    height: 0.343421
    finger_angle: 180 # hanyang
    z_angle: +13.1825

